# ==============================================================================
# Android Build Patcher
# ==============================================================================
# Patches the generated Flutter/Android project to fix Windows build issues:
# 1. Kotlin incremental compilation cross-drive crashes
# 2. AAPT2 timeout issues with resource compilation
# 3. Gradle daemon instability
#
# Called by clean_build.ps1 after bootstrap generation, before Gradle build
# ==============================================================================

param(
    [string]$AndroidPath = "build_src\build\flutter\android",
    [switch]$NoSplash = $false
)

$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "============================================================================" -ForegroundColor Cyan
Write-Host "  Android Build Patcher" -ForegroundColor Cyan
Write-Host "============================================================================" -ForegroundColor Cyan
Write-Host ""

# Check if Android project exists
if (-not (Test-Path $AndroidPath)) {
    Write-Host "[ERROR] Android project not found at: $AndroidPath" -ForegroundColor Red
    Write-Host "This script must be called after Flutter bootstrap generation." -ForegroundColor Red
    exit 1
}

Write-Host "[PATCH] Target: $AndroidPath" -ForegroundColor Gray
Write-Host ""

# ==============================================================================
# Step 1: Patch gradle.properties
# ==============================================================================
Write-Host "[1/3] Patching gradle.properties..." -ForegroundColor Yellow

$GradlePropsPath = Join-Path $AndroidPath "gradle.properties"

# Read existing properties
$ExistingProps = @{}
$OtherLines = @()

if (Test-Path $GradlePropsPath) {
    foreach ($Line in Get-Content $GradlePropsPath) {
        $Trimmed = $Line.Trim()
        if ($Trimmed -and -not $Trimmed.StartsWith("#")) {
            if ($Trimmed -match "^([^=]+)=(.*)$") {
                $Key = $Matches[1].Trim()
                $Value = $Matches[2].Trim()
                $ExistingProps[$Key] = $Value
            } else {
                $OtherLines += $Line
            }
        } elseif ($Trimmed.StartsWith("#") -or [string]::IsNullOrWhiteSpace($Trimmed)) {
            $OtherLines += $Line
        }
    }
}

# Define required properties (these fix the build issues)
$RequiredProps = [ordered]@{
    "kotlin.incremental" = "false"
    "org.gradle.caching" = "false"
    "org.gradle.daemon" = "false"
    "org.gradle.workers.max" = "2"
    "org.gradle.jvmargs" = "-Xmx4g -Dfile.encoding=UTF-8"
}

# Merge: update existing, keep others, add missing
$FinalProps = [ordered]@{}
foreach ($Key in $ExistingProps.Keys) {
    if ($RequiredProps.Contains($Key)) {
        $FinalProps[$Key] = $RequiredProps[$Key]
    } else {
        $FinalProps[$Key] = $ExistingProps[$Key]
    }
}
foreach ($Key in $RequiredProps.Keys) {
    if (-not $FinalProps.Contains($Key)) {
        $FinalProps[$Key] = $RequiredProps[$Key]
    }
}

# Write updated properties
$NewContent = @()
$NewContent += "# gradle.properties (patched for Windows build reliability)"
$NewContent += "# Generated by patch_android_build.ps1"
$NewContent += ""
$NewContent += "# ============================================================================"
$NewContent += "# Build Reliability Fixes"
$NewContent += "# ============================================================================"
foreach ($Key in $FinalProps.Keys) {
    $NewContent += "$Key=$($FinalProps[$Key])"
    if ($RequiredProps.Contains($Key)) {
        Write-Host "  Set: $Key = $($FinalProps[$Key])" -ForegroundColor Gray
    }
}

Set-Content -Path $GradlePropsPath -Value ($NewContent -join "`n") -NoNewline
Write-Host "  gradle.properties updated successfully" -ForegroundColor Green
Write-Host ""

# ==============================================================================
# Step 2: Patch AndroidManifest.xml
# ==============================================================================
Write-Host "[2/4] Patching AndroidManifest.xml..." -ForegroundColor Yellow

$ManifestPath = Join-Path $AndroidPath "app\src\main\AndroidManifest.xml"

if (Test-Path $ManifestPath) {
    $ManifestContent = Get-Content $ManifestPath -Raw

    $Changed = $false

    # Add extractNativeLibs="true" to <application> tag
    if ($ManifestContent -notmatch 'extractNativeLibs') {
        $ManifestContent = $ManifestContent -replace '(<application\b)', '$1 android:extractNativeLibs="true"'
        Write-Host "  Added: android:extractNativeLibs=true" -ForegroundColor Gray
        $Changed = $true
    }

    # Add usesCleartextTraffic="true" to <application> tag
    if ($ManifestContent -notmatch 'usesCleartextTraffic') {
        $ManifestContent = $ManifestContent -replace '(<application\b)', '$1 android:usesCleartextTraffic="true"'
        Write-Host "  Added: android:usesCleartextTraffic=true" -ForegroundColor Gray
        $Changed = $true
    }

    if ($Changed) {
        Set-Content -Path $ManifestPath -Value $ManifestContent -NoNewline
        Write-Host "  AndroidManifest.xml patched" -ForegroundColor Green
    } else {
        Write-Host "  AndroidManifest.xml already has required attributes" -ForegroundColor Gray
    }
} else {
    Write-Host "  [WARN] AndroidManifest.xml not found at: $ManifestPath" -ForegroundColor Yellow
}
Write-Host ""

# ==============================================================================
# Step 3: Remove splash resources if NO_SPLASH is enabled
# ==============================================================================
Write-Host "[3/4] Processing splash resources..." -ForegroundColor Yellow

if ($NoSplash -or $env:NO_SPLASH -eq "1") {
    Write-Host "  NO_SPLASH mode enabled - removing splash resources" -ForegroundColor Yellow
    
    $ResPath = Join-Path $AndroidPath "app\src\main\res"
    if (Test-Path $ResPath) {
        $SplashFiles = Get-ChildItem -Path $ResPath -Recurse -Include "splash.png","android12splash.png" -ErrorAction SilentlyContinue
        
        $RemovedCount = 0
        foreach ($File in $SplashFiles) {
            try {
                Remove-Item $File.FullName -Force
                Write-Host "  Removed: $($File.FullName.Replace($ResPath, 'res'))" -ForegroundColor Gray
                $RemovedCount++
            } catch {
                Write-Host "  Warning: Could not remove $($File.Name)" -ForegroundColor Yellow
            }
        }
        
        if ($RemovedCount -gt 0) {
            Write-Host "  Removed $RemovedCount splash resource(s)" -ForegroundColor Green
        } else {
            Write-Host "  No splash resources found to remove" -ForegroundColor Gray
        }
    } else {
        Write-Host "  Resources folder not found, skipping splash removal" -ForegroundColor Gray
    }
} else {
    Write-Host "  Keeping splash resources (use NO_SPLASH=1 to disable)" -ForegroundColor Gray
}
Write-Host ""

# ==============================================================================
# Step 4: Clean stale build caches
# ==============================================================================
Write-Host "[4/4] Cleaning stale build caches..." -ForegroundColor Yellow

$CachePaths = @(
    (Join-Path $AndroidPath ".gradle"),
    (Join-Path $AndroidPath "app\build"),
    (Join-Path $AndroidPath "build")
)

$CleanedCount = 0
foreach ($CachePath in $CachePaths) {
    if (Test-Path $CachePath) {
        try {
            Remove-Item -Path $CachePath -Recurse -Force -ErrorAction Stop
            Write-Host "  Removed: $($CachePath.Replace($AndroidPath, '.'))" -ForegroundColor Gray
            $CleanedCount++
        } catch {
            Write-Host "  Warning: Could not remove cache: $($CachePath.Replace($AndroidPath, '.'))" -ForegroundColor Yellow
        }
    }
}

if ($CleanedCount -gt 0) {
    Write-Host "  Cleaned $CleanedCount cache folder(s)" -ForegroundColor Green
} else {
    Write-Host "  No stale caches found" -ForegroundColor Gray
}
Write-Host ""

Write-Host "============================================================================" -ForegroundColor Green
Write-Host "  Android Build Patching Complete" -ForegroundColor Green
Write-Host "============================================================================" -ForegroundColor Green
Write-Host ""

exit 0
